# markdown: redcarpet
# highlighter: pygments # or rouge or null
exclude:
  - node_modules
  - gulpfile.js
  - gulpconfig.json
  - package.json
  - config.rb
  - npm-debug.log
  - README.md

title: DojoCon Japan 2016
description: DojoCon Japan 2016
url: https://dojocon-japan.github.io/dojocon2016teaser
baseurl: /